files:
  - server/*.js
  - server/lib/*.js
  - server/lib/**/*.js
  - server/config/*.js
  - server/config/**/*.js
  - server/controllers/*.js
  - server/controllers/**/*.js

branches:
  - master

packageJson: package.json

articles:
  - Readme: README.md
