version: '3'

services:
  bhima:
    #build: .
    image: imaworldhealth/bhima:latest
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=STRICT_ALL_TABLES,NO_UNSIGNED_SUBTRACTION
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldata:/var/lib/mysql/
      - "./temp:/docker-entrypoint-initdb.d"
    environment:
      # - MYSQL_ROOT_PASSWORD=2fe88872-0598-11ee-b0cf-47268d06eac1
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
  redis:
    image: redis:latest
    restart: always

volumes:
  mysqldata:
