version: '3.8'

services:
  bhima:
    build: .
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:8
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sql-mode=STRICT_ALL_TABLES,NO_UNSIGNED_SUBTRACTION
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldata:/var/lib/mysql/
      - "./temp/docker-build.sql:/docker-entrypoint-initdb.d/bhima.sql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
  redis:
    image: redis:latest
    restart: always

volumes:
  mysqldata:
