#!/usr/bin/perl -i
#
# PARTIALLY convert protractor tests to playwright tests

my $is_spec_file = "$ARGV[0]" =~ /.*\.spec\.js\z/;

my $header1 = 'const { chromium } = require(\'@playwright/test\');
';

my $header2 = 'const { test, expect } = require(\'@playwright/test\');
const TU = require(\'../shared/TestUtils\');
const { by } = require(\'../shared/TestUtils\');

';

my $header3 = 'test.beforeAll(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  TU.registerPage(page);
  await TU.login();
});

';

sub write_headers {
    if ($is_spec_file) {
      print $header1;
    }
    print $header2;
    if ($is_spec_file) {
      print $header3;
    }
}

while (<>) {
  write_headers() if $. == 1;  # Insert needed imports, etc
    next if /\/\* global .* \*\//;  # Omit
    next if /^[ ]*const { expect } = require\('chai'\);/;  # Omit
    next if /const FU = require.*/;  # Omit
    s|FU\.|TU.|g;
    s|^(\s*)describe|\1test.describe|g;
    s|^(\s*)before\(\(\)|\1test.beforeEach(async ()|g;
    s|helpers\.getCurrentPath|TU.getCurrentPath|g;
    s|helpers\.navigate\(|TU.navigate(|g;
    s|^(\s*)it\(|\1test(|g;
    s|\.to\.equal|.toBe|g;
    s|element\(|TU.locator(|g;
    s|browser\.findElement\(|TU.locator(|g;
    s|\.getText\(|.innerText(|g;
    s|by\.css\(([^)]+)\)|\1|g;
    s|= \$\(([^\)]+)\);|= await TU.locator(\1);|g;
    s|\.sendKeys\(|.fill(|g;
    s|row\.dropdown\(\)\.click\(\)|row.dropdown()|g;
    s|row\.edit\(\)\.click\(\)|row.edit()|g;
    s|row\.remove\(\)\.click\(\)|row.remove()|g;
    s| \$\(| TU.locator(|g;
    s|\.\$\(|.locator(|g;
    print;
}

