angular.module('bhima.services')
.factory('AuthInjectorFactory', AuthInjectorFactory);

AuthInjectorFactory.$inject = [
  '$rootScope','$q',  '$location', 'SessionService'
];

function AuthInjectorFactory($rootScope, $q, $location, Session) {
  return {
    responseError : function (res) {
      console.log('[INTERCEPTOR] Received HTTP error', res.status);

      // if we hit an error generated by a session, redirect the user to the /login page
      if (res.status === 401 && res.data.code === 'ERR_NOT_AUTHENTICATED') {
        console.log('[AUTH] Session is not defined.  Redirecting to /login');

        // kill the old session to avoid residual data
        Session.destroy();

        // redirect to login
        $location.url('/login');
      }
      return $q.reject(res);
    }
  };
}

