angular.module('bhima.services')
.factory('AuthInjectorFactory', AuthInjectorFactory);

AuthInjectorFactory.$inject = [
  '$rootScope','$q',  '$location'
];

function AuthInjectorFactory($rootScope, $q, $location) {
  return {
    responseError : function (res) {
      console.log('[INTERCEPTOR] Received HTTP error', res.status);

      // if we hit an error generated by a session, redirect the user to the /login page
      if (res.status === 401) {
        console.log('[AUTH] Session is not defined.  Redirecting to /login');

        // redirect to login
        $location.url('/login');
      }

      return $q.reject(res);
    }
  };
}

