angular.module('bhima.services')
.factory('AuthInjectorFactory', AuthInjectorFactory);

AuthInjectorFactory.$inject = [ '$rootScope','$q' ];

function AuthInjectorFactory($rootScope, $q) {
  return {
    // if we hit an error generated by a session, redirect the user to the /login page
    responseError : function (res) {
      if (res.status === 401) { $rootScope.$emit('session.destroy'); }
      return $q.reject(res);
    }
  };
}

