angular.module('bhima.services')
  .service('ColorService', ColorService);

ColorService.$inject = [
  '$translate',
];

function ColorService($translate) {
  const service = this;
  service.list = [
    { name : $translate.instant('COLORS.ALICEBLUE'), value : '#F0F8FF' },
    { name : $translate.instant('COLORS.ANTIQUEWHITE'), value : '#FAEBD7' },
    { name : $translate.instant('COLORS.AQUAMARINE'), value : '#7FFFD4' },
    { name : $translate.instant('COLORS.AQUA'), value : '#00ffff' },
    { name : $translate.instant('COLORS.AZURE'), value : '#F0FFFF' },
    { name : $translate.instant('COLORS.BEIGE'), value : '#F5F5DC' },
    { name : $translate.instant('COLORS.BISQUE'), value : '#FFE4C4' },
    { name : $translate.instant('COLORS.BLANCHEDALMOND'), value : '#FFEBCD' },
    { name : $translate.instant('COLORS.BLUE'), value : '#0000FF' },
    { name : $translate.instant('COLORS.BLUEVIOLET'), value : '#8A2BE2' },
    { name : $translate.instant('COLORS.BROWN'), value : '#A52A2A' },
    { name : $translate.instant('COLORS.BURLYWOOD'), value : '#DEB887' },
    { name : $translate.instant('COLORS.CADETBLUE'), value : '#5F9EA0' },
    { name : $translate.instant('COLORS.CHARTREUSE'), value : '#7FFF00' },
    { name : $translate.instant('COLORS.CHOCOLATE'), value : '#D2691E' },
    { name : $translate.instant('COLORS.CORAL'), value : '#FF7F50' },
    { name : $translate.instant('COLORS.CORNFLOWERBLUE'), value : '#6495ED' },
    { name : $translate.instant('COLORS.CORNSILK'), value : '#FFF8DC' },
    { name : $translate.instant('COLORS.CRIMSON'), value : '#dc143c' },
    { name : $translate.instant('COLORS.CYAN'), value : '#00FFFF' },
    { name : $translate.instant('COLORS.DARKBLUE'), value : '#00008B' },
    { name : $translate.instant('COLORS.DARKCYAN'), value : '#008B8B' },
    { name : $translate.instant('COLORS.DARKGOLDENROD'), value : '#B8860B' },
    { name : $translate.instant('COLORS.DARKGRAY'), value : '#A9A9A9' },
    { name : $translate.instant('COLORS.DARKGREEN'), value : '#006400' },
    { name : $translate.instant('COLORS.DARKKHAKI'), value : '#BDB76B' },
    { name : $translate.instant('COLORS.DARKMAGENTA'), value : '#8B008B' },
    { name : $translate.instant('COLORS.DARKOLIVEGREEN'), value : '#556B2F' },
    { name : $translate.instant('COLORS.DARKORANGE'), value : '#FF8C00' },
    { name : $translate.instant('COLORS.DARKORCHID'), value : '#9932CC' },
    { name : $translate.instant('COLORS.DARKRED'), value : '#8B0000' },
    { name : $translate.instant('COLORS.DARKSALMON'), value : '#E9967A' },
    { name : $translate.instant('COLORS.DARKSEAGREEN'), value : '#8FBC8F' },
    { name : $translate.instant('COLORS.DARKSLATEBLUE'), value : '#483D8B' },
    { name : $translate.instant('COLORS.DARKSLATEGRAY'), value : '#2F4F4F' },
    { name : $translate.instant('COLORS.DARKTURQUOISE'), value : '#00CED1' },
    { name : $translate.instant('COLORS.DARKVIOLET'), value : '#9400D3' },
    { name : $translate.instant('COLORS.DEEPPINK'), value : '#FF1493' },
    { name : $translate.instant('COLORS.DEEPSKYBLUE'), value : '#00BFFF' },
    { name : $translate.instant('COLORS.DIMGRAY'), value : '#696969' },
    { name : $translate.instant('COLORS.DODGERBLUE'), value : '#1E90FF' },
    { name : $translate.instant('COLORS.FIREBRICK'), value : '#B22222' },
    { name : $translate.instant('COLORS.FLORALWHITE'), value : '#FFFAF0' },
    { name : $translate.instant('COLORS.FORESTGREEN'), value : '#228b22' },
    { name : $translate.instant('COLORS.FUCHSIA'), value : '#FF00FF' },
    { name : $translate.instant('COLORS.GAINSBORO'), value : '#DCDCDC' },
    { name : $translate.instant('COLORS.GHOSTWHITE'), value : '#F8F8FF' },
    { name : $translate.instant('COLORS.GOLDENROD'), value : '#DAA520' },
    { name : $translate.instant('COLORS.GOLD'), value : '#FFD700' },
    { name : $translate.instant('COLORS.GRAY'), value : '#808080' },
    { name : $translate.instant('COLORS.GRAY'), value : '#808080' },
    { name : $translate.instant('COLORS.GREEN'), value : '#008000' },
    { name : $translate.instant('COLORS.GREENYELLOW'), value : '#ADFF2F' },
    { name : $translate.instant('COLORS.HONEYDEW'), value : '#F0FFF0' },
    { name : $translate.instant('COLORS.HOTPINK'), value : '#FF69B4' },
    { name : $translate.instant('COLORS.INDIANRED'), value : '#CD5C5C' },
    { name : $translate.instant('COLORS.INDIGO'), value : '#4B0082' },
    { name : $translate.instant('COLORS.IVORY'), value : '#FFFFF0' },
    { name : $translate.instant('COLORS.KHAKI'), value : '#F0E68C' },
    { name : $translate.instant('COLORS.LAVENDERBLUSH'), value : '#FFF0F5' },
    { name : $translate.instant('COLORS.LAVENDER'), value : '#E6E6FA' },
    { name : $translate.instant('COLORS.LAWNGREEN'), value : '#7CFC00' },
    { name : $translate.instant('COLORS.LEMONCHIFFON'), value : '#FFFACD' },
    { name : $translate.instant('COLORS.LIGHTBLUE'), value : '#ADD8E6' },
    { name : $translate.instant('COLORS.LIGHTCORAL'), value : '#F08080' },
    { name : $translate.instant('COLORS.LIGHTCYAN'), value : '#E0FFFF' },
    { name : $translate.instant('COLORS.LIGHTGOLDENRODYELLOW'), value : '#FAFAD2' },
    { name : $translate.instant('COLORS.LIGHTGREEN'), value : '#90EE90' },
    { name : $translate.instant('COLORS.LIGHTGREY'), value : '#D3D3D3' },
    { name : $translate.instant('COLORS.LIGHTPINK'), value : '#FFB6C1' },
    { name : $translate.instant('COLORS.LIGHTSALMON'), value : '#FFA07A' },
    { name : $translate.instant('COLORS.LIGHTSEAGREEN'), value : '#20B2AA' },
    { name : $translate.instant('COLORS.LIGHTSKYBLUE'), value : '#87CEFA' },
    { name : $translate.instant('COLORS.LIGHTSLATEGRAY'), value : '#778899' },
    { name : $translate.instant('COLORS.LIGHTSTEELBLUE'), value : '#B0C4DE' },
    { name : $translate.instant('COLORS.LIGHTYELLOW'), value : '#FFFFE0' },
    { name : $translate.instant('COLORS.LIMEGREEN'), value : '#32CD32' },
    { name : $translate.instant('COLORS.LIME'), value : '#00ff00' },
    { name : $translate.instant('COLORS.LINEN'), value : '#FAF0E6' },
    { name : $translate.instant('COLORS.MAGENTA'), value : '#FF00FF' },
    { name : $translate.instant('COLORS.MAROON'), value : '#800000' },
    { name : $translate.instant('COLORS.MEDIUMAQUAMARINE'), value : '#66CDAA' },
    { name : $translate.instant('COLORS.MEDIUMBLUE'), value : '#0000CD' },
    { name : $translate.instant('COLORS.MEDIUMORCHID'), value : '#BA55D3' },
    { name : $translate.instant('COLORS.MEDIUMPURPLE'), value : '#9370DB' },
    { name : $translate.instant('COLORS.MEDIUMSEAGREEN'), value : '#3CB371' },
    { name : $translate.instant('COLORS.MEDIUMSLATEBLUE'), value : '#7B68EE' },
    { name : $translate.instant('COLORS.MEDIUMSPRINGGREEN'), value : '#00FA9A' },
    { name : $translate.instant('COLORS.MEDIUMTURQUOISE'), value : '#48D1CC' },
    { name : $translate.instant('COLORS.MEDIUMVIOLETRED'), value : '#C71585' },
    { name : $translate.instant('COLORS.MIDNIGHTBLUE'), value : '#191970' },
    { name : $translate.instant('COLORS.MINTCREAM'), value : '#F5FFFA' },
    { name : $translate.instant('COLORS.MISTYROSE'), value : '#FFE4E1' },
    { name : $translate.instant('COLORS.MOCCASIN'), value : '#FFE4B5' },
    { name : $translate.instant('COLORS.NAVAJOWHITE'), value : '#FFDEAD' },
    { name : $translate.instant('COLORS.NAVY'), value : '#000080' },
    { name : $translate.instant('COLORS.OLDLACE'), value : '#FDF5E6' },
    { name : $translate.instant('COLORS.OLIVEDRAB'), value : '#6B8E23' },
    { name : $translate.instant('COLORS.OLIVE'), value : '#808000' },
    { name : $translate.instant('COLORS.ORANGERED'), value : '#FF4500' },
    { name : $translate.instant('COLORS.ORANGE'), value : '#FFA500' },
    { name : $translate.instant('COLORS.ORCHID'), value : '#DA70D6' },
    { name : $translate.instant('COLORS.PALEGOLDENROD'), value : '#EEE8AA' },
    { name : $translate.instant('COLORS.PALEGREEN'), value : '#98FB98' },
    { name : $translate.instant('COLORS.PALETURQUOISE '), value : '#AFEEEE' },
    { name : $translate.instant('COLORS.PALEVIOLETRED'), value : '#DB7093' },
    { name : $translate.instant('COLORS.PAPAYAWHIP'), value : '#FFEFD5' },
    { name : $translate.instant('COLORS.PEACHPUFF'), value : '#FFDAB9' },
    { name : $translate.instant('COLORS.PERU'), value : '#CD853F' },
    { name : $translate.instant('COLORS.PINK'), value : '#FFC0CB' },
    { name : $translate.instant('COLORS.PLUM'), value : '#DDA0DD' },
    { name : $translate.instant('COLORS.POWDERBLUE'), value : '#B0E0E6' },
    { name : $translate.instant('COLORS.PURPLE'), value : '#800080' },
    { name : $translate.instant('COLORS.RED'), value : '#ff0000' },
    { name : $translate.instant('COLORS.ROSYBROWN'), value : '#BC8F8F' },
    { name : $translate.instant('COLORS.ROYALBLUE'), value : '#4169E1' },
    { name : $translate.instant('COLORS.SADDLEBROWN'), value : '#8B4513' },
    { name : $translate.instant('COLORS.SALMON'), value : '#FA8072' },
    { name : $translate.instant('COLORS.SANDYBROWN'), value : '#F4A460' },
    { name : $translate.instant('COLORS.SEAGREEN'), value : '#2E8B57' },
    { name : $translate.instant('COLORS.SEASHELL'), value : '#FFF5EE' },
    { name : $translate.instant('COLORS.SIENNA'), value : '#A0522D' },
    { name : $translate.instant('COLORS.SILVER'), value : '#C0C0C0' },
    { name : $translate.instant('COLORS.SKYBLUE'), value : '#87CEEB' },
    { name : $translate.instant('COLORS.SLATEBLUE'), value : '#6a5acd' },
    { name : $translate.instant('COLORS.SLATEGRAY'), value : '#708090' },
    { name : $translate.instant('COLORS.SNOW'), value : '#FFFAFA' },
    { name : $translate.instant('COLORS.SPRINGGREEN'), value : '#00FF7F' },
    { name : $translate.instant('COLORS.STEELBLUE'), value : '#4682B4' },
    { name : $translate.instant('COLORS.TAN'), value : '#D2B48C' },
    { name : $translate.instant('COLORS.TEAL'), value : '#008080' },
    { name : $translate.instant('COLORS.THISTLE'), value : '#D8BFD8' },
    { name : $translate.instant('COLORS.TOMATO'), value : '#FF6347' },
    { name : $translate.instant('COLORS.TURQUOISE'), value : '#40E0D0' },
    { name : $translate.instant('COLORS.VIOLET'), value : '#EE82EE' },
    { name : $translate.instant('COLORS.WHEAT'), value : '#F5DEB3' },
    { name : $translate.instant('COLORS.WHITESMOKE'), value : '#F5F5F5' },
    { name : $translate.instant('COLORS.WHITE'), value : '#FFFFFF' },
    { name : $translate.instant('COLORS.YELLOWGREEN'), value : '#9acd32' },
    { name : $translate.instant('COLORS.YELLOW'), value : '#ffff00' },
  ];

  service.list.sort((a, b) => {
    const nameA = a.name.toUpperCase();
    const nameB = b.name.toUpperCase();
    if (nameA < nameB) {
      return -1;
    }
    if (nameA > nameB) {
      return 1;
    }
    return 0;
  });

  return service;
}
