module.exports = rubircs();

function rubircs() {
  return [
    {
      indice_type :  'is_base_index',
      label :  'PAYROLL_RUBRIC.BASE_INDEX',
      abbr :  'Indice de base',
      is_indice : 1,
      position : 1,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_day_index',
      label :  'PAYROLL_RUBRIC.DAY_INDEX',
      abbr :  'Indice du jr',
      is_indice : 1,
      position : 2,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_reagistered_index',
      label :  'PAYROLL_RUBRIC.REAGISTERED_INDEX',
      abbr :  'Indice Réagisté',
      is_indice : 1,
      position : 3,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_responsability',
      label :  'PAYROLL_RUBRIC.RESPONSABILITY',
      abbr :  'Responsabilité',
      is_indice : 1,
      position : 4,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_other_profits',
      label :  'PAYROLL_RUBRIC.OTHER_PROFIT',
      abbr :  'Autre Profit',
      indice_to_grap : 1,
      is_indice : 1,
      position : 5,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_total_code',
      label :  'PAYROLL_RUBRIC.TOTAL_CODE',
      abbr :  'TtCode',
      is_indice : 1,
      position : 6,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_day_worked',
      label :  'PAYROLL_RUBRIC.DAY_WORKED',
      abbr :  'Jr presté',
      indice_to_grap   :  1,
      is_indice : 1,
      position : 7,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_extra_day',
      label :  'PAYROLL_RUBRIC.EXTRA_DAY',
      abbr :  'jr Suppl',
      indice_to_grap   :  1,
      is_indice : 1,
      position : 8,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_total_days',
      label :  'PAYROLL_RUBRIC.TOTAL_DAYS',
      abbr :  'ttjr',
      is_indice : 1,
      position : 9,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_pay_rate',
      label :  'PAYROLL_RUBRIC.PAY_RATE',
      abbr :  'TxPaie',
      is_indice : 1,
      position : 10,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_gross_salary',
      label :  'PAYROLL_RUBRIC.GROSS_SALARY',
      abbr :  'Brute',
      is_indice : 1,
      position : 11,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_number_of_days',
      label :  'PAYROLL_RUBRIC.NUMBER_OF_DAYS',
      abbr :  'NbrJr',
      is_indice : 1,
      position : 12,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_seniority_index',
      label :  'PAYROLL_RUBRIC.SENIORITY_INDEX',
      abbr :  'Senior',
      is_indice : 1,
      position : 13,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_relative_point',
      label :  'PAYROLL_RUBRIC.RELATIVE_POINT',
      abbr :  'RelativeP',
      is_indice : 1,
      position : 14,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_fixed_bonus',
      label :  'PAYROLL_RUBRIC.FIXED_BONUS',
      abbr :  'fixedBonus',
      is_indice : 1,
      position : 15,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_performance_bonus',
      label :  'PAYROLL_RUBRIC.PERFORMANCE_BONUS',
      abbr :  'PERF_BONUS',
      is_indice : 1,
      position : 16,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_individual_performance',
      label :  'PAYROLL_RUBRIC.INDIVIDUAL_PERFORMANCE',
      abbr :  'IND_PERF',
      is_indice : 1,
      position : 17,
      is_monetary_value : 0,
    },
    {
      indice_type :  'is_performance_rate',
      label :  'PAYROLL_RUBRIC.IS_PERFORMANCE_RATE',
      abbr :  'IND_PERF_RATE',
      is_indice : 1,
      position : 17,
      is_monetary_value : 0,
    },
  ];
}
